[platformio]
default_envs = m5stack-core-esp32

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED

[env:microduino-core-esp32]
board = microduino-core-esp32
upload_port = COM5
monitor_port = COM5
build_src_filter =
    -<*>
    +<microduino_core_esp32_test/>

[env:esp32-wroom-32]
board = esp32dev
build_src_filter =
    -<*>
    +<esp32_wroom_32_test/>

[env:m5stack-core-esp32]
board = m5stack-core-esp32
upload_port = COM6
monitor_port = COM6
lib_deps =
    ${env.lib_deps}
    m5stack/M5Stack
build_src_filter =
    -<*>
    +<m5stack_core_esp32_test/>
