[platformio]
default_envs = m5stack-core-esp32

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED

[env:microduino-core-esp32]
board = microduino-core-esp32
upload_port = COM5
monitor_port = COM5
lib_deps =
    ${env.lib_deps}
    someweisguy/esp_dmx @ ^4.1.0
build_src_filter =
    -<*>
    +<microduino_core_esp32_test/>

[env:microduino-core-esp32-dmx-spotlight-test]
board = microduino-core-esp32
upload_port = COM5
monitor_port = COM5
lib_deps =
    ${env.lib_deps}
    someweisguy/esp_dmx @ ^4.1.0
build_src_filter =
    -<*>
    +<microduino_core_esp32_dmx_spotlight_test/>

[env:microduino-core-esp32-stepper-pin-diagnostic]
board = microduino-core-esp32
upload_port = COM5
monitor_port = COM5
lib_deps =
    ${env.lib_deps}
build_src_filter =
    -<*>
    +<microduino_core_esp32_stepper_pin_diagnostic/>

[env:esp32-wroom-32]
board = esp32dev
build_src_filter =
    -<*>
    +<esp32_wroom_32_test/>

[env:m5stack-core-esp32]
board = m5stack-core-esp32
board_build.partitions = huge_app.csv
upload_port = COM6
monitor_port = COM6
lib_deps =
    ${env.lib_deps}
    m5stack/M5Stack
build_src_filter =
    -<*>
    +<m5stack_core_esp32_test/>

[env:esp32-s3-n16r8-vibration]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
upload_port = COM11
monitor_port = COM11
lib_deps =
    ${env.lib_deps}
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
build_src_filter =
    -<*>
    +<esp32_s3_n16r8_vibration_sensor_test/>
