[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED

[env:microduino-core-esp32]
board = microduino-core-esp32

[env:esp32-wroom-32]
board = esp32dev

[env:m5stack-core-esp32]
board = m5stack-core-esp32
